name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Before you start, read [the rules](https://github.com/BartoszCichecki/LenovoLegionToolkit/blob/master/CONTRIBUTING.md) for contributing.
  - type: textarea
    id: troubleshoot
    attributes:
      label: What is wrong?
      description: Provide detailed description of what is wrong or does not work as expected.
      placeholder: Provide detailed description of what is wrong or does not work as expected.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug?
      description: Describe how to reproduce the behavior. Be as specific as possible and provide as many details as possible.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the behavior that you expected?
      description: Describe what did you expect would happen.
      placeholder: Describe what did you expect would happen.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: If applicable, add screenshots or other relevant information to help explain your problem.
